# Generated by Django 4.2.1 on 2023-08-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_language_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='images/')),
                ('link', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='finish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.CharField(max_length=100),
        ),
    ]
