# Generated by Django 4.2.1 on 2023-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_socialnetworks_alter_education_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='instagramEmbed',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
