# Generated by Django 4.2.1 on 2023-08-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_news_instagramembed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
