# Generated by Django 4.2.1 on 2023-08-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_portfolio_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
